CC=		gcc
SRCS=		$(wildcard *.c)
OBJS=		$(SRCS:.c = .o)
BIN=		vfpolicyd
CFLAGS+=	-Wall -Werror -fno-builtin-strlen
LDFLAGS+=	-lev

default:	$(OBJS)
		$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) -o $(BIN)

%.o:		%.c
		$(CC) -c $< $(CFLAGS)

clean:
	rm -f *.o
	rm -f $(BIN)
