PROG=			vfpolicyd
SRCS=			vfpolicyd.c
PROGNAME=		vfpolicyd

PREFIX=         /usr/local
INCDIR=			${PREFIX}/include
BINDIR=			${PREFIX}/sbin
LIBDIR=			${PREFIX}/lib

DEBUG=			1

CFLAGS+=		-Wall -Wmissing-prototypes -Wno-uninitialized
CFLAGS+=		-Wunreachable-code
CFLAGS+=		-Wstrict-prototypes -Wunused -ansi -pedantic -I${INCDIR} -DDEBUG=\"${DEBUG}\"

LDFLAGS+=		-L${LIBDIR} -lev

.include <bsd.prog.mk>
